apiVersion: v1
kind: Pod
metadata:
 name: nginx-md
 labels:
    env: dev
    app: web
spec:
 containers:
  - name: nginx
    image: nginx:latest
    ports:
     - name: nginxport
       containerPort: 80
       protocol: TCP
