apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: demo
  labels:
    app: deployment
spec:
 replicas: 3
 selector:
  matchLabels:
    app: deployment
 template:
  metadata:
   labels:
    app: deployment
  spec:
    containers:
    - name: nginx
      image: nginx
